### ISSUE TITLE
Other comment for event

### ISSUE THREAD

**Issue by koderik** [isektionen/iare-se#11]
# Regarding the feature to submit an extra comment to the event osa.

I have made a mockup for how the comment input could be implemented on the last stage of the event checkout.
![chrome_dxNr9PnPIG](https://user-images.githubusercontent.com/77754074/146683402-094a88bb-d046-4625-98e9-a948c0c0693b.png)

The mockup was made by adding a header and an input below the ticket image as seen here *from row 171 to 179 in **src/components/event/steps/OrderSummary.tsx***.
![Code_GiMGFuA0uk](https://user-images.githubusercontent.com/77754074/146683480-dabe95f8-38b1-43ad-a055-00007a243751.png)

However, this component would have to be connected to the backend. The text for the header and the placeholder would need to be fetched from the cms as it could vary between events and languages. The submitted text would also need to be saved somewhere connected to the specific order. The option to enable/disable the user to write a comment should also be added to the event osa creator in the cms.

Please add to the issue when more progress is made!

**Comment by landeholt** [comment]
0b9eabfc26483e5d28c9d5296ef2a2895eeee2fe solves this
