### ISSUE TITLE
Document page not working

### ISSUE THREAD

**Issue by koderik** [isektionen/iare-se#14]
The document page is down on https://www.iare.se/chapter/document
![image](https://user-images.githubusercontent.com/77754074/149998691-6add837d-534f-44c7-b477-e07e7c3d7b7e.png)
Running the site as dev gives the following error:
![image](https://user-images.githubusercontent.com/77754074/149998764-d65aedaf-1494-40f0-8964-b9aad6eb0e79.png)

**Comment by landeholt** [comment]
ca49bf0a10f9e29b2a4bb423dc37eea4b97bc5bb solves this
